version: "3.8"

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-09-01T23-53-36Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
      - gamestation_network


services:
  mongodb:
    image: mongo:latest
    container_name: gamestation_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: userdb 
    ports:
      - "27017:27017"
    networks:
      - gamestation_network

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
# services:
  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: gamestation_minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    networks:
      - gamestation_network

  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: gamestation_minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    networks:
      - gamestation_network

  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: gamestation_minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    networks:
      - gamestation_network

  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: gamestation_minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    networks:
      - gamestation_network

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    container_name: gamestation_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - gamestation_network

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:



networks:
  gamestation_network:
    driver: bridge