
apiVersion: apps/v1
kind: Deployment 
metadata:
    name: second-app-deployment 
spec: 
    replicas: 1
    selector:  // have to give
        matchLebels:
            app: second-app
            tier: backend
    template:
        metadata:
            labels:
                app: second-app
                tier: backend
        spec:
            containers:
                - name: kube-gamestation
                  image: shahriarraka/gamestation
