version: "3.8"



services:
  mongodb:
    image: mongo:latest
    container_name: gamestation_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: userdb 
    volumes:
      - /docker/gamestationmongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - gamestation_network
  minio:
    image: quay.io/minio/minio:latest
    container_name: gamestation_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=miniosecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /docker/gamestationminio:/data
    
    networks:
      - gamestation_network


networks:
  gamestation_network:
    driver: bridge